#window
WINDOW_WIDTH = 250
WINDOW_HEIGHT = 250

#background
BACKGROUND_SCROLL_SPEED = 2

#player
PLAYER_TOTAL_FRAMES = 6
PLAYER_WIDTH = 25
PLAYER_POS_X = 40
PLAYER_POS_Y = WINDOW_HEIGHT - 70

#floor
INITIAL_FLOOR_WIDTH = WINDOW_WIDTH
FLOOR_MARGIN = 2